module EXU(
    input wire [31:0] i_src1,
    input wire [31:0] i_src2,
    input wire [31:0] i_imm,
    input wire [31:0] i_offset,
    input wire [31:0] i_pc_data,
    input wire [5:0] i_shamt,
    input wire [31:0] i_csr_data,
    input wire i_addi_signal,
    input wire i_jalr_signal,
    input wire i_lb_signal,
    input wire i_lh_signal,
    input wire i_lw_signal,
    input wire i_lbu_signal,
    input wire i_lhu_signal,
    input wire i_xori_signal,
    input wire i_ori_signal,
    input wire i_andi_signal,
    input wire i_slli_signal,
    input wire i_srli_signal,
    input wire i_srai_signal,
    input wire i_slti_signal,
    input wire i_sltiu_signal,
    input wire i_beq_signal,
    input wire i_bne_signal,
    input wire i_blt_signal,
    input wire i_bge_signal,
    input wire i_bltu_signal,
    input wire i_bgeu_signal,
    input wire i_jal_signal,
    input wire i_sw_signal,
    input wire i_sh_signal,
    input wire i_sb_signal,
    input wire i_and_signal,
    input wire i_or_signal,
    input wire i_xor_signal,
    input wire i_srl_signal,
    input wire i_sra_signal,
    // input wire i_mul_signal,
    // input wire i_mulh_signal,
    // input wire i_mulhu_signal,
    // input wire i_mulhsu_signal,
    // input wire i_div_signal,
    // input wire i_divu_signal,
    // input wire i_rem_signal,
    // input wire i_remu_signal,
    input wire i_auipc_signal,
    input wire i_lui_signal,
    input wire i_add_signal,
    input wire i_sub_signal,
    input wire i_sll_signal,
    input wire i_slt_signal,
    input wire i_sltu_signal,
    input wire i_ebreak_signal,
    input wire i_csrrs_signal,
    input wire i_csrrw_signal,
    input wire i_ecall_signal,
    input wire i_mret_signal,
    output wire o_B_jump_signal,
    output wire o_halt_signal,
    output wire [31:0] o_data

);

alu alu_u(
    .i_src1(i_src1),
    .i_src2(i_src2),
    .i_imm(i_imm),
    .i_offset(i_offset),
    .i_pc_data(i_pc_data),
    .i_shamt(i_shamt),
    .i_csr_data(i_csr_data),
    .i_addi_signal(i_addi_signal),
    .i_jalr_signal(i_jalr_signal),
    .i_lb_signal(i_lb_signal),
    .i_lh_signal(i_lh_signal),
    .i_lw_signal(i_lw_signal),
    .i_lbu_signal(i_lbu_signal),
    .i_lhu_signal(i_lhu_signal),
    .i_xori_signal(i_xori_signal),
    .i_ori_signal(i_ori_signal),
    .i_andi_signal(i_andi_signal),
    .i_slli_signal(i_slli_signal),
    .i_srli_signal(i_srli_signal),
    .i_srai_signal(i_srai_signal),
    .i_slti_signal(i_slti_signal),
    .i_sltiu_signal(i_sltiu_signal),
    .i_beq_signal(i_beq_signal),
    .i_bne_signal(i_bne_signal),
    .i_blt_signal(i_blt_signal),
    .i_bge_signal(i_bge_signal),
    .i_bltu_signal(i_bltu_signal),
    .i_bgeu_signal(i_bgeu_signal),
    .i_jal_signal(i_jal_signal),
    .i_sw_signal(i_sw_signal),
    .i_sh_signal(i_sh_signal),
    .i_sb_signal(i_sb_signal),
    .i_and_signal(i_and_signal),
    .i_or_signal(i_or_signal),
    .i_xor_signal(i_xor_signal),
    .i_srl_signal(i_srl_signal),
    .i_sra_signal(i_sra_signal),
    // .i_mul_signal(i_mul_signal),
    // .i_mulh_signal(i_mulh_signal),
    // .i_mulhu_signal(i_mulhu_signal),
    // .i_mulhsu_signal(i_mulhsu_signal),
    // .i_div_signal(i_div_signal),
    // .i_divu_signal(i_divu_signal),
    // .i_rem_signal(i_rem_signal),
    // .i_remu_signal(i_remu_signal),
    .i_auipc_signal(i_auipc_signal),
    .i_lui_signal(i_lui_signal),
    .i_add_signal(i_add_signal),
    .i_sub_signal(i_sub_signal),
    .i_sll_signal(i_sll_signal),
    .i_slt_signal(i_slt_signal),
    .i_sltu_signal(i_sltu_signal),
    .i_ebreak_signal(i_ebreak_signal),
    .i_csrrs_signal(i_csrrs_signal),
    .i_csrrw_signal(i_csrrw_signal),
    .i_ecall_signal(i_ecall_signal),
    .i_mret_signal(i_mret_signal),
    .o_B_jump_signal(o_B_jump_signal),
    .o_halt_signal(o_halt_signal),
    .o_data(o_data)
);


endmodule
